# Generated by Django 5.0.3 on 2024-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_age_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
