# Generated by Django 5.0.3 on 2024-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='users_avatars'),
        ),
    ]
