# Generated by Django 5.0.3 on 2024-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_myuser_age_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password1',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='password2',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
