# Generated by Django 5.0.3 on 2024-04-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_myuser_password1_myuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='password2',
        ),
    ]
