# Generated by Django 5.0.3 on 2024-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_myuser_password1_remove_myuser_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateUserInTelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ON', models.BooleanField()),
                ('OFF', models.BooleanField()),
            ],
        ),
    ]
