# Generated by Django 5.0.3 on 2024-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_stateuserintelegrambot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateuserintelegrambot',
            name='OFF',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stateuserintelegrambot',
            name='ON',
            field=models.BooleanField(default=False),
        ),
    ]
