# Generated by Django 5.0.3 on 2024-04-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_stateuserintelegrambot_off_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateuserintelegrambot',
            old_name='OFF',
            new_name='STATE_USER',
        ),
        migrations.RemoveField(
            model_name='stateuserintelegrambot',
            name='ON',
        ),
    ]
