# Generated by Django 5.0.3 on 2024-04-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_stateuserintelegrambot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateuserintelegrambot',
            name='user',
        ),
    ]
