# Generated by Django 5.0.3 on 2024-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='about_product',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
