# Generated by Django 5.0.3 on 2024-04-03 17:19

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_about_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='article',
            field=products.models.RandomLatinCharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
