# Generated by Django 5.0.3 on 2024-04-03 17:30

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=products.models.RandomLatinCharField(max_length=20, unique=True),
        ),
    ]
