# Generated by Django 5.0.3 on 2024-04-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
