# Generated by Django 5.0.3 on 2024-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_stripe_product_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
